gt_it:
    resource: "@GtItBundle/Resources/config/routing.yml"
    prefix:   /
utilisateurs:
    resource: "@UtilisateursBundle/Resources/config/routing.yml"
    prefix:   /
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

    

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /ab  # <-- change this value
