gt_it_admin_threads:
    resource: "@GtItBundle/Resources/config/routing/threads.yml"
    prefix:   /admin/threads/{comment_id}

gt_it_admin_tag:
    resource: "@GtItBundle/Resources/config/routing/tag.yml"
    prefix:   /admin/tag

gt_it_admin_comment:
    resource: "@GtItBundle/Resources/config/routing/comment.yml"
    prefix:   /admin/comment/{item}



gt_it_admin_blog:
    resource: "@GtItBundle/Resources/config/routing/blog.yml"
    prefix:   /admin/blog



gt_it_first:
    pattern:  /
    defaults: { _controller: GtItBundle:First:first }
gt_it_a:
    pattern:  /a
    defaults: { _controller: GtItBundle:Blog:ahmed }



gt_it_blog:
    pattern:  /blog
    defaults: { _controller: GtItBundle:Blog:blog }
gt_it_blogSingle:
    pattern:  /blog/{id}.{format}
    defaults: { _controller: GtItBundle:Blog:blogSingle }
    
    requirements:
        format: html|xml


