<?php

namespace Gt\ItBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{ public function byIdblog($date)
    {
        $qb = $this->createQueryBuilder('u')
                ->select('u')
                ->where('u.idblog = :date')
                
                ->orderBy('u.id')
                ->setParameter('date', $date);
        
        return $qb->getQuery()->getResult();
    }
    public function byCount($i)
    {
        $qb = $this->createQueryBuilder('u')
                ->select('COUNT(u)')
                ->where('u.idblog = :i')
                
                
                ->setParameter('i', $i);
        
        return $qb->getQuery()->getResult();
    }

        public function byId($i)
    {
        $qb = $this->createQueryBuilder('u')
                ->select('u')
                ->where('u.blog_id = :i')
                
                
                ->setParameter('i', $i);
        
        return $qb->getQuery()->getResult();
    }
}
