<?php

namespace Gt\ItBundle\Entity;

/**
 * dRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class dRepository extends \Doctrine\ORM\EntityRepository
{
}
