<?php

namespace Gt\ItBundle\Entity;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends \Doctrine\ORM\EntityRepository
{public function byTime()
    {
        $qb = $this->createQueryBuilder('u')
                ->select('u')
                ->orderBy('u.date');
        
        return $qb->getQuery()->getResult();
    }
 public function byLimit()
    {
        $qb = $this->createQueryBuilder('u')
                ->select('u')
                ->orderBy('u.date')->setMaxResults(5);
        
        return $qb->getQuery()->getResult();
    }
}
