admin_user:
    pattern:  /
    defaults: { _controller: "UtilisateursBundle:Utilisateurs:index" }

admin_user_show:
    pattern:  /{id}/show
    defaults: { _controller: "UtilisateursBundle:Utilisateurs:show" }

admin_user_new:
    pattern:  /new
    defaults: { _controller: "UtilisateursBundle:Utilisateurs:new" }

admin_user_create:
    pattern:  /create
    defaults: { _controller: "UtilisateursBundle:Utilisateurs:create" }
    requirements: { _method: post }

admin_user_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "UtilisateursBundle:Utilisateurs:edit" }

admin_user_update:
    pattern:  /{id}/update
    defaults: { _controller: "UtilisateursBundle:Utilisateurs:update" }
    requirements: { _method: post|put }

admin_user_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "UtilisateursBundle:Utilisateurs:delete" }
    requirements: { _method: post|delete }
